[oneid-uat]
user = iqs
group = www-data
listen = /run/php/php8.3-fpm-oneid-uat.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
clear_env = yes
env[ONEID_RUNTIME_FILE] = /var/www/oneid-uat/.private/runtime.php
php_admin_value[error_log] = /var/www/oneid-uat/storage/logs/php-error.log
php_admin_flag[log_errors] = on
php_admin_flag[display_errors] = off
