<?php

return [
    'wrappers' => [
        ['public' => 'public/index.php', 'target' => 'index.php', 'fragment' => "'/index.php'"],
        ['public' => 'public/api.php', 'target' => 'api.php', 'fragment' => "'/api.php'"],
        ['public' => 'public/idms.php', 'target' => 'idms.php', 'fragment' => "'/idms.php'"],
        ['public' => 'public/skp_api.php', 'target' => 'skp_api.php', 'fragment' => "'/skp_api.php'"],
        ['public' => 'public/admin/dashboard.php', 'target' => 'admin/dashboard.php', 'fragment' => "'/admin/dashboard.php'"],
        ['public' => 'public/admin/logout.php', 'target' => 'app/Auth/LogoutEndpoint.php', 'fragment' => "'/app/Auth/LogoutEndpoint.php'"],
        ['public' => 'public/admin/user_list.php', 'target' => 'admin/user_list.php', 'fragment' => "'/admin/user_list.php'"],
        ['public' => 'public/page/dashboard.php', 'target' => 'page/dashboard.php', 'fragment' => "'/page/dashboard.php'"],
        ['public' => 'public/page/logout.php', 'target' => 'app/Auth/LogoutEndpoint.php', 'fragment' => "'/app/Auth/LogoutEndpoint.php'"],
        ['public' => 'public/lib/q_func.php', 'target' => 'lib/q_func.php', 'fragment' => "'/lib/q_func.php'"],
        ['public' => 'public/lib/sso_IDP_index.php', 'target' => 'lib/sso_IDP_index.php', 'fragment' => "'/lib/sso_IDP_index.php'"],
        ['public' => 'public/lib/sso_IDP_sub.php', 'target' => 'lib/sso_IDP_sub.php', 'fragment' => "'/lib/sso_IDP_sub.php'"],
    ],
    'http' => [
        ['path' => '/', 'statuses' => [200], 'type' => 'text/html'],
        ['path' => '/index.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/page/dashboard.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/page/logout.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/admin/dashboard.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/admin/logout.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/admin/user_list.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/api.php', 'statuses' => [400], 'type' => 'application/json'],
        ['path' => '/idms.php', 'statuses' => [200], 'type' => 'application/json'],
        ['path' => '/skp_api.php', 'statuses' => [400], 'type' => 'application/json'],
        ['path' => '/lib/q_func.php', 'statuses' => [405], 'type' => 'application/json'],
        ['path' => '/lib/sso_IDP_index.php', 'statuses' => [200], 'type' => 'text/html'],
        ['path' => '/lib/sso_IDP_sub.php', 'statuses' => [302], 'type' => 'text/html', 'location' => '/'],
        ['path' => '/assetsM/css/custom.css', 'statuses' => [200], 'type' => 'text/css'],
        ['path' => '/dist/css/style.css', 'statuses' => [200], 'type' => 'text/css'],
        ['path' => '/public_docs/MANUAL_SALAM.pdf', 'statuses' => [200], 'type' => 'application/pdf'],
        ['path' => '/videos/video1.mp4', 'statuses' => [200], 'type' => 'video/mp4'],
        ['path' => '/favicon.ico', 'statuses' => [200], 'type' => 'image/x-icon'],
    ],
    'boundary' => [
        '/README.md',
        '/package.json',
        '/sso_db.sql',
        '/docs/',
        '/bootstrap/paths.php',
        '/storage/',
        '/tools/restructure_smoke.php',
        '/diag/agent.php',
        '/test.php',
        '/atest.php',
        '/public_img/test.php',
        '/assetsM/test.php',
        '/dist/test.php',
        '/vendors/bower_components/filament-tablesaw/demo/issues/charset-test-issue-106.php',
        '/vendors/bower_components/morris.js/spec/viz/run.sh',
    ],
];
