server {
    listen 443 ssl http2;
    server_name oneid.example.edu.my;

    root /var/www/app/oneid/public;
    index index.php;
    client_max_body_size 6m;

    # Tetapkan ssl_certificate dan ssl_certificate_key mengikut host.

    location / {
        if (-f $request_filename.php) {
            rewrite ^(.+?)/?$ $1.php last;
        }
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* ^/(?:assetsM|dist|img|vendors|public_docs|public_img|videos)/.*\.(?:php[0-9]?|phtml|phar|cgi|pl|py|sh)$ {
        return 404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm-oneid.sock;
    }

    location ~ /\. {
        deny all;
    }
}
