<?php
declare(strict_types=1);
namespace OneId\App\Auth;
use Throwable;
final class Admin2faBootstrapService{
 public function __construct(private readonly object $operation){}
 public function enable(string $admin,string $password,int $version,string $reason,string $typed,string $changeId,string $ip):array{$cid=bin2hex(random_bytes(8));$reason=trim($reason);$typed=trim($typed);$changeId=trim($changeId);if($changeId!=='ONEID-F7-2FA-20260720-01')throw new AdminStepUpException('BOOTSTRAP_CHANGE_ID_INVALID',$cid);if($typed!=='ENABLE ADMIN 2FA')throw new AdminStepUpException('BOOTSTRAP_TYPED_CONFIRMATION_INVALID',$cid);if(strlen($reason)<10||strlen($reason)>500)throw new AdminStepUpException('BOOTSTRAP_REASON_INVALID',$cid);if(filter_var($ip,FILTER_VALIDATE_IP)===false)throw new AdminStepUpException('BOOTSTRAP_IP_INVALID',$cid);$started=false;
  try{$this->operation->beginTransaction();$started=true;$user=$this->operation->admin_mfa_enrollment_context_for_update($admin);$status=$this->operation->admin_step_up_factor_status($admin);$config=$this->operation->get_system_config_for_update();if(!is_array($user)||!is_array($status)||!is_array($config)||(int)$user['u_type']!==1||(int)$user['avail_status']!==1)throw new AdminStepUpException('BOOTSTRAP_ADMIN_INVALID',$cid);if((int)$status['admin_2fa_enabled']!==0)throw new AdminStepUpException('BOOTSTRAP_ALREADY_ENABLED',$cid);if((int)$status['totp_available']!==1||filter_var((string)$user['email'],FILTER_VALIDATE_EMAIL)===false)throw new AdminStepUpException('BOOTSTRAP_FACTORS_REQUIRED',$cid);if(!\oneid_password_verify($password,(string)$user['u_password']))throw new AdminStepUpException('BOOTSTRAP_PASSWORD_INVALID',$cid);if((int)$config['configuration_version']!==$version||$this->operation->admin_2fa_enable_by_version((int)$config['id'],$version)!==1)throw new AdminStepUpException('BOOTSTRAP_CONFIGURATION_STALE',$cid);$this->operation->configuration_history_record(['version_before'=>$version,'version_after'=>$version+1,'actor_id'=>$admin,'ip_address'=>$ip,'action_name'=>'ADMIN_2FA_BOOTSTRAP_ENABLE','outcome'=>'SUCCESS','reason_code'=>'ADMIN_2FA_BOOTSTRAP_ENABLED','change_reason'=>$reason,'before'=>['admin_2fa_enabled'=>0],'after'=>['admin_2fa_enabled'=>1],'correlation_id'=>$cid]);if($this->operation->syslog_record(51,"admin=$admin action=admin_2fa_bootstrap outcome=enabled change_id=$changeId correlation=$cid",$ip)!==1)throw new AdminStepUpException('STEP_UP_AUDIT_FAILED',$cid);$this->operation->commit();$started=false;return['status'=>1,'code'=>'ADMIN_2FA_BOOTSTRAP_ENABLED','configuration_version'=>$version+1,'correlation_id'=>$cid];
  }catch(AdminStepUpException $e){if($started)$this->operation->rollback();throw$e;}catch(Throwable $e){if($started)$this->operation->rollback();throw new AdminStepUpException('BOOTSTRAP_FAILED',$cid);}}
}
