<?php
declare(strict_types=1);
namespace OneId\App\Auth;
use Throwable;
final class AdminStepUpTotpService{
 private const PURPOSES=['ADMIN_ACCESS','SECURITY_CONFIGURATION_CHANGE','ACTIVE_SESSION_REVOCATION'];private $clock;
 public function __construct(private readonly object $operation,private readonly TotpSecretCipher $cipher,?callable $clock=null){$this->clock=$clock??static fn():int=>time();}
 public function verify(string $admin,string $purpose,string $code,string $sessionId,string $userAgent,string $ip):array{$cid=bin2hex(random_bytes(8));$purpose=strtoupper(trim($purpose));if(!in_array($purpose,self::PURPOSES,true))throw new AdminStepUpException('STEP_UP_PURPOSE_INVALID',$cid);if(preg_match('/\A[0-9]{6}\z/',$code)!==1)throw new AdminStepUpException('STEP_UP_VERIFICATION_FAILED',$cid);if($sessionId===''||strlen($sessionId)>256)throw new AdminStepUpException('STEP_UP_SESSION_INVALID',$cid);if(filter_var($ip,FILTER_VALIDATE_IP)===false)throw new AdminStepUpException('STEP_UP_IP_INVALID',$cid);$session=hash('sha256',$sessionId);$browser=hash('sha256',substr($userAgent,0,1000));$started=false;
  try{$this->operation->beginTransaction();$started=true;$state=$this->operation->admin_step_up_factor_status($admin);if(!is_array($state)||(int)($state['admin_2fa_enabled']??0)!==1||(int)($state['u_type']??0)!==1||(int)($state['avail_status']??0)!==1)throw new AdminStepUpException('STEP_UP_DISABLED',$cid);$lifetime=(int)($state['admin_step_up_lifetime_minutes']??15);if(!in_array($lifetime,[5,10,15,30],true))throw new AdminStepUpException('STEP_UP_CONFIGURATION_INVALID',$cid);$factor=$this->operation->admin_mfa_active_factor_for_update($admin);if(!is_array($factor))throw new AdminStepUpException('STEP_UP_FACTOR_UNAVAILABLE',$cid);$secret=$this->cipher->decrypt($factor['encrypted_secret'],$factor['secret_nonce'],$factor['key_version']);$step=Totp::matchTimeStep($secret,$code,($this->clock)(),1,$factor['last_used_time_step']===null?null:(int)$factor['last_used_time_step']);unset($secret);if($step===null){$this->audit(47,$admin,$purpose,'invalid_or_replayed',$cid,$ip);$this->operation->commit();$started=false;throw new AdminStepUpException('STEP_UP_VERIFICATION_FAILED',$cid);}if($this->operation->admin_mfa_record_factor_use((int)$factor['factor_id'],$step)!==1)throw new AdminStepUpException('STEP_UP_REPLAYED',$cid);if($this->operation->admin_step_up_create_grant(['grant_id'=>bin2hex(random_bytes(32)),'admin_user_id'=>$admin,'session_binding_hash'=>$session,'browser_digest'=>$browser,'purpose'=>$purpose,'verified_factor'=>'TOTP','lifetime_minutes'=>$lifetime,'correlation_id'=>$cid])!==1)throw new AdminStepUpException('STEP_UP_GRANT_CREATE_FAILED',$cid);$this->audit(46,$admin,$purpose,'verified',$cid,$ip);$this->operation->commit();$started=false;return['status'=>1,'code'=>'STEP_UP_VERIFIED','purpose'=>$purpose,'factor'=>'TOTP','grant_expires_in_seconds'=>$lifetime*60,'correlation_id'=>$cid];
  }catch(AdminStepUpException $e){if($started)$this->operation->rollback();throw$e;}catch(Throwable $e){if($started)$this->operation->rollback();throw new AdminStepUpException('STEP_UP_VERIFICATION_FAILED',$cid);}}
 private function audit(int $event,string $admin,string $purpose,string $outcome,string $cid,string $ip):void{if($this->operation->syslog_record($event,sprintf('admin=%s action=admin_step_up purpose=%s outcome=%s correlation=%s',$admin,$purpose,$outcome,$cid),$ip)!==1)throw new AdminStepUpException('STEP_UP_AUDIT_FAILED',$cid);}
}
