<?php
declare(strict_types=1);
namespace OneId\App\Auth;
use Throwable;
final class AdminMfaPreferenceService{
 public function __construct(private readonly object $operation){}
 public function status(string $admin):array{$s=$this->operation->admin_step_up_factor_status($admin);if(!is_array($s)||(int)($s['u_type']??0)!==1||(int)($s['avail_status']??0)!==1)throw new AdminStepUpException('STEP_UP_ADMIN_NOT_ELIGIBLE',bin2hex(random_bytes(8)));$email=trim((string)($s['email']??''));$lifetime=(int)($s['admin_step_up_lifetime_minutes']??15);if(!in_array($lifetime,[5,10,15,30],true))throw new AdminStepUpException('STEP_UP_CONFIGURATION_INVALID',bin2hex(random_bytes(8)));return['status'=>1,'feature_enabled'=>(int)$s['admin_2fa_enabled']===1,'configuration_version'=>(int)$s['configuration_version'],'admin_step_up_lifetime_minutes'=>$lifetime,'email_available'=>filter_var($email,FILTER_VALIDATE_EMAIL)!==false,'masked_email'=>$this->mask($email),'totp_available'=>(int)$s['totp_available']===1,'totp_factor_id'=>$s['totp_factor_id']===null?null:(int)$s['totp_factor_id'],'preferred_factor'=>$s['preferred_factor']?:null];}
 public function select(string $admin,string $factor,?string $currentPassword,string $sessionId,string $userAgent,string $ip):array{$cid=bin2hex(random_bytes(8));$factor=strtoupper(trim($factor));if(!in_array($factor,['EMAIL_OTP','TOTP'],true))throw new AdminStepUpException('MFA_PREFERENCE_INVALID',$cid);if(filter_var($ip,FILTER_VALIDATE_IP)===false||$sessionId==='')throw new AdminStepUpException('MFA_PREFERENCE_CONTEXT_INVALID',$cid);$session=hash('sha256',$sessionId);$browser=hash('sha256',substr($userAgent,0,1000));$started=false;
  try{$this->operation->beginTransaction();$started=true;$s=$this->operation->admin_mfa_enrollment_context_for_update($admin);$status=$this->operation->admin_step_up_factor_status($admin);if(!is_array($s)||!is_array($status)||(int)$s['u_type']!==1||(int)$s['avail_status']!==1)throw new AdminStepUpException('STEP_UP_ADMIN_NOT_ELIGIBLE',$cid);$enabled=(int)$status['admin_2fa_enabled']===1;if($enabled){$auth=$this->operation->admin_step_up_authorization_state($admin,$session,$browser,'SECURITY_CONFIGURATION_CHANGE');if(!is_array($auth)||(int)($auth['exact_valid']??0)<1)throw new AdminStepUpException('STEP_UP_REQUIRED',$cid);}elseif(!password_verify((string)$currentPassword,(string)$s['u_password'])&&!(function_exists('oneid_password_verify')&&\oneid_password_verify((string)$currentPassword,(string)$s['u_password'])))throw new AdminStepUpException('TOTP_CURRENT_PASSWORD_INVALID',$cid);if($factor==='EMAIL_OTP'&&filter_var((string)$s['email'],FILTER_VALIDATE_EMAIL)===false)throw new AdminStepUpException('STEP_UP_FACTOR_UNAVAILABLE',$cid);if($factor==='TOTP'&&(int)($status['totp_available']??0)!==1)throw new AdminStepUpException('STEP_UP_FACTOR_UNAVAILABLE',$cid);$this->operation->admin_mfa_set_preference($admin,$factor,$admin,$cid);if($this->operation->syslog_record(50,"admin=$admin action=mfa_preference factor=$factor correlation=$cid",$ip)!==1)throw new AdminStepUpException('STEP_UP_AUDIT_FAILED',$cid);$this->operation->commit();$started=false;return['status'=>1,'code'=>'MFA_PREFERENCE_UPDATED','preferred_factor'=>$factor,'correlation_id'=>$cid];
  }catch(AdminStepUpException $e){if($started)$this->operation->rollback();throw$e;}catch(Throwable $e){if($started)$this->operation->rollback();throw new AdminStepUpException('MFA_PREFERENCE_FAILED',$cid);}}
 private function mask(string $email):?string{if(filter_var($email,FILTER_VALIDATE_EMAIL)===false)return null;[$l,$d]=explode('@',$email,2);return substr($l,0,1).str_repeat('*',max(2,min(8,strlen($l)-1))).'@'.$d;}
}
