INSERT INTO syslog_event_conf(syslog_event_id,syslog_event_name) VALUES
    (55,'USER_MFA_PRIMARY_AUTH_PENDING'),
    (56,'USER_MFA_EMAIL_CHALLENGE'),
    (57,'USER_MFA_EMAIL_VERIFY'),
    (58,'USER_MFA_TOTP_VERIFY'),
    (59,'USER_MFA_LOGIN_COMPLETE'),
    (60,'USER_MFA_FACTOR_ENROLL'),
    (61,'USER_MFA_FACTOR_REVOKE'),
    (62,'USER_MFA_PREFERENCE_CHANGE'),
    (63,'USER_MFA_ADMIN_RECOVERY'),
    (64,'USER_MFA_POLICY_CHANGE'),
    (65,'USER_MFA_RETENTION_PURGE');
