-- Additive production plan, observer OFF. Do not apply historical migrations in bulk.
DELIMITER $$
CREATE TABLE mobile_oidc_mutex(singleton_id TINYINT UNSIGNED NOT NULL PRIMARY KEY) ENGINE=InnoDB$$
INSERT INTO mobile_oidc_mutex VALUES(1)$$
CREATE TABLE mobile_oidc_records(record_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,record_json JSON NOT NULL,updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB$$
CREATE TABLE mobile_oidc_control (singleton_id TINYINT PRIMARY KEY,observer_enabled TINYINT NOT NULL DEFAULT 0,policy_epoch BIGINT UNSIGNED NOT NULL DEFAULT 1) ENGINE=InnoDB$$
INSERT INTO mobile_oidc_control VALUES(1,0,1)$$
CREATE TABLE mobile_oidc_identity_epoch (u_id VARCHAR(20) NOT NULL PRIMARY KEY,generation CHAR(48) CHARACTER SET ascii NOT NULL,security_version BIGINT UNSIGNED NOT NULL DEFAULT 1,deleted TINYINT NOT NULL DEFAULT 0,updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)) ENGINE=InnoDB$$
INSERT INTO mobile_oidc_identity_epoch(u_id,generation) SELECT u_id,HEX(RANDOM_BYTES(24)) FROM user_tbl$$
CREATE TRIGGER mobile_oidc_control_bu BEFORE UPDATE ON mobile_oidc_control FOR EACH ROW BEGIN IF OLD.observer_enabled<>NEW.observer_enabled THEN SET NEW.policy_epoch=OLD.policy_epoch+1; END IF; END$$
CREATE TRIGGER mobile_oidc_user_ai AFTER INSERT ON user_tbl FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE generation=HEX(RANDOM_BYTES(24)),security_version=security_version+1,deleted=0; END IF; END$$
CREATE TRIGGER mobile_oidc_user_au AFTER UPDATE ON user_tbl FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (NOT (BINARY OLD.u_id <=> BINARY NEW.u_id) OR NOT (BINARY OLD.avail_status <=> BINARY NEW.avail_status) OR NOT (BINARY OLD.password_change_required <=> BINARY NEW.password_change_required) OR NOT (BINARY OLD.u_type <=> BINARY NEW.u_type) OR NOT (BINARY OLD.u_category <=> BINARY NEW.u_category) OR NOT (BINARY OLD.data2 <=> BINARY NEW.data2) OR NOT (BINARY OLD.data3 <=> BINARY NEW.data3) OR NOT (BINARY OLD.data4 <=> BINARY NEW.data4) OR NOT (BINARY OLD.data5 <=> BINARY NEW.data5) OR NOT (BINARY OLD.u_password <=> BINARY NEW.u_password) AND COALESCE(@oneid_mobile_password_rehash,0)<>1) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; IF OLD.u_id<>NEW.u_id THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END IF; END$$
CREATE TRIGGER mobile_oidc_user_ad AFTER DELETE ON user_tbl FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; UPDATE mobile_oidc_identity_epoch SET deleted=1 WHERE u_id=OLD.u_id; END IF; END$$
CREATE TRIGGER mobile_oidc_factor_ai AFTER INSERT ON user_mfa_factors FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_factor_au AFTER UPDATE ON user_mfa_factors FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (NOT (BINARY OLD.u_id <=> BINARY NEW.u_id) OR NOT (BINARY OLD.factor_type <=> BINARY NEW.factor_type) OR NOT (BINARY OLD.factor_status <=> BINARY NEW.factor_status) OR NOT (BINARY OLD.encrypted_secret <=> BINARY NEW.encrypted_secret) OR NOT (BINARY OLD.secret_nonce <=> BINARY NEW.secret_nonce) OR NOT (BINARY OLD.key_version <=> BINARY NEW.key_version)) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; IF OLD.u_id<>NEW.u_id THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END IF; END$$
CREATE TRIGGER mobile_oidc_factor_ad AFTER DELETE ON user_mfa_factors FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_membership_ai AFTER INSERT ON user_external_identity FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_membership_au AFTER UPDATE ON user_external_identity FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (NOT (OLD.u_id <=> NEW.u_id) OR NOT (OLD.source_code <=> NEW.source_code) OR NOT (OLD.source_active <=> NEW.source_active)) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; IF OLD.u_id<>NEW.u_id THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END IF; END$$
CREATE TRIGGER mobile_oidc_membership_ad AFTER DELETE ON user_external_identity FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_exemption_ai AFTER INSERT ON user_login_mfa_exemptions FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_exemption_au AFTER UPDATE ON user_login_mfa_exemptions FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; IF OLD.u_id<>NEW.u_id THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END IF; END$$
CREATE TRIGGER mobile_oidc_exemption_ad AFTER DELETE ON user_login_mfa_exemptions FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_pilot_ai AFTER INSERT ON user_login_mfa_pilot_users FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_pilot_au AFTER UPDATE ON user_login_mfa_pilot_users FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(NEW.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; IF OLD.u_id<>NEW.u_id THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END IF; END$$
CREATE TRIGGER mobile_oidc_pilot_ad AFTER DELETE ON user_login_mfa_pilot_users FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 AND (TRUE) THEN INSERT INTO mobile_oidc_identity_epoch(u_id,generation) VALUES(OLD.u_id,HEX(RANDOM_BYTES(24))) ON DUPLICATE KEY UPDATE security_version=security_version+1; END IF; END$$
CREATE TRIGGER mobile_oidc_policy_ai AFTER INSERT ON user_login_mfa_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_policy_au AFTER UPDATE ON user_login_mfa_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_policy_ad AFTER DELETE ON user_login_mfa_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_category_ai AFTER INSERT ON user_login_mfa_category_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_category_au AFTER UPDATE ON user_login_mfa_category_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_category_ad AFTER DELETE ON user_login_mfa_category_policy FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_operational_ai AFTER INSERT ON user_mfa_policy_change_requests FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_operational_au AFTER UPDATE ON user_mfa_policy_change_requests FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_operational_ad AFTER DELETE ON user_mfa_policy_change_requests FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_source_ai AFTER INSERT ON external_source FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_source_au AFTER UPDATE ON external_source FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
CREATE TRIGGER mobile_oidc_source_ad AFTER DELETE ON external_source FOR EACH ROW BEGIN IF (SELECT observer_enabled FROM mobile_oidc_control WHERE singleton_id=1)=1 THEN UPDATE mobile_oidc_control SET policy_epoch=policy_epoch+1 WHERE singleton_id=1; END IF; END$$
DELIMITER ;
