<?php
// Private disposable MySQL only: included after PDO adapter tests.
use OneId\App\Auth\MobileOidc\{MobilePasswordRecovery,LifecycleSchema,PdoIdentitySource};
$pdo->exec('CREATE TABLE sys_config(singleton_key INT PRIMARY KEY,password_reset_email_enabled INT)');
$pdo->exec('INSERT INTO sys_config VALUES(1,1)');
$pdo->exec('CREATE TABLE user_mfa_policy_change_requests(id INT PRIMARY KEY)');
$pdo->exec('CREATE TABLE otp_codes(otp_id INT AUTO_INCREMENT PRIMARY KEY,u_id VARCHAR(20),otp_create_date DATETIME,otp_consumed_at DATETIME NULL)');
$pdo->exec('ALTER TABLE token_tbl ADD user_id VARCHAR(20), ADD status INT, ADD ended_at DATETIME NULL, ADD end_reason VARCHAR(30) NULL');
$pdo->exec('CREATE TABLE user_password_history(id INT AUTO_INCREMENT PRIMARY KEY,user_id VARCHAR(20),password_hash VARCHAR(255),changed_at DATETIME)');
foreach(LifecycleSchema::statements() as $sql)$pdo->exec($sql);
$pdo->exec('UPDATE mobile_oidc_control SET observer_enabled=1');
$pdo->exec("UPDATE user_tbl SET avail_status=1,password_change_required=0,data5='fixture@example.invalid' WHERE u_id='STAFF_FIXTURE'");
$delivery=new class implements \OneId\App\Auth\MobileOidc\OtpDelivery {
 public string $code='';public int $sends=0;public bool $success=true;
 public function send(string $destination,string $name,string $otp):bool{$this->code=$otp;$this->sends++;return $this->success;}
};
$source=new PdoIdentitySource($pdo,'OFF',false,fn()=>true,true);
$recovery=new MobilePasswordRecovery($pdo,$source,$delivery,$key);
$startRecovery=function()use($store,$key,$recovery){$tx=bin2hex(random_bytes(32));$store->transaction(fn()=>$store->put('tx:'.$tx,['state'=>'PASSWORD','expires'=>time()+300,'binding'=>hash_hmac('sha256',"secret\0agent",$key)]));return $recovery->begin($tx,'secret','agent');};
$clearRates=fn()=>$pdo->exec("DELETE FROM mobile_oidc_records WHERE record_key LIKE 'recovery-rate:%'");
$id=$startRecovery();check(is_string($id),'recovery requires valid bound login transaction');
check($recovery->request($id,'MISSING','fixture-ip')==='OTP' && $delivery->sends===0,'unknown account gets generic result without sending email');
check($recovery->reset($id,'Replacement!2026z','Replacement!2026z')==='ERROR','password reset requires verified recovery proof');
for($i=0;$i<5;$i++)$result=$recovery->verify($id,'000000');
check($result==='ERROR','five wrong codes exhaust challenge');
$clearRates();$id=$startRecovery();check($recovery->request($id,'STAFF_FIXTURE','fixture-ip')==='OTP' && $delivery->sends===1,'active OneID account receives recovery code');
check($recovery->verify($id,$delivery->code)==='NEW','correct delivered OTP authorizes reset');
check($recovery->verify($id,$delivery->code)==='ERROR','OTP cannot be replayed');
check($recovery->reset($id,'short','short')==='QUALITY','shared password policy rejects weak password');
check($recovery->reset($id,'Replacement!2026z','different')==='MISMATCH','confirmation mismatch rejected');
$pdo->exec("UPDATE token_tbl SET user_id='STAFF_FIXTURE',status=1");
$version=(int)$pdo->query("SELECT security_version FROM mobile_oidc_identity_epoch WHERE u_id='STAFF_FIXTURE'")->fetchColumn();
check($recovery->reset($id,'Replacement!2026z','Replacement!2026z')==='DONE','verified recovery resets password');
check(oneid_password_verify('Replacement!2026z',$pdo->query("SELECT u_password FROM user_tbl WHERE u_id='STAFF_FIXTURE'")->fetchColumn()),'new password stored using shared hashing');
check((int)$pdo->query('SELECT status FROM token_tbl')->fetchColumn()===0,'password reset revokes existing web session');
check((int)$pdo->query("SELECT security_version FROM mobile_oidc_identity_epoch WHERE u_id='STAFF_FIXTURE'")->fetchColumn()>$version,'password reset advances mobile security epoch');
check($recovery->reset($id,'Another!2026z','Another!2026z')==='ERROR','reset proof is single use');
$clearRates();$id=$startRecovery();$recovery->request($id,'STAFF_FIXTURE','fixture-ip');$pdo->exec("UPDATE user_tbl SET avail_status=0 WHERE u_id='STAFF_FIXTURE'");
check($recovery->verify($id,$delivery->code)!=='NEW','disabled account rejected after OTP delivery');
$pdo->exec("UPDATE user_tbl SET avail_status=1 WHERE u_id='STAFF_FIXTURE'");
$clearRates();$id=$startRecovery();$delivery->success=false;$recovery->request($id,'STAFF_FIXTURE','fixture-ip');check($recovery->verify($id,$delivery->code)!=='NEW','failed SMTP delivery cannot authorize reset');
$delivery->success=true;
$clearRates();$id=$startRecovery();$recovery->request($id,'STAFF_FIXTURE','fixture-ip');
$store->transaction(function()use($store,$id){$r=$store->get('recovery:'.$id);$r['otp_expires']=time()-1;$store->put('recovery:'.$id,$r);});
check($recovery->verify($id,$delivery->code)==='ERROR','expired recovery OTP rejected');
$clearRates();$id=$startRecovery();$recovery->request($id,'STAFF_FIXTURE','fixture-ip');$recovery->verify($id,$delivery->code);
check($recovery->reset($id,'Replacement!2026z','Replacement!2026z')==='REUSED','current password reuse rejected');
$pdo->exec("UPDATE user_tbl SET data5='changed@example.invalid' WHERE u_id='STAFF_FIXTURE'");
check($recovery->reset($id,'Another!2026z','Another!2026z')==='ERROR','email changed after verification invalidates reset proof');
$clearRates();$first=$startRecovery();$second=$startRecovery();$beforeSends=$delivery->sends;
$recovery->request($first,'STAFF_FIXTURE','fixture-ip');$recovery->request($second,'STAFF_FIXTURE','fixture-ip');
check($delivery->sends===$beforeSends+1,'per-account cooldown prevents repeated emails');
$store->transaction(function()use($store,$first){$r=$store->get('recovery:'.$first);$r['expires']=time()-1;$store->put('recovery:'.$first,$r);});
check($recovery->verify($first,$delivery->code)==='ERROR','expired recovery transaction rejected');
$clearRates();$id=$startRecovery();
$r=$store->transaction(fn()=>$store->get('recovery:'.$id));$txId=$r['tx'];
check(!$recovery->cancel($id,$txId,'wrong','agent'),'recovery cancel rejects wrong browser binding');
check($recovery->cancel($id,$txId,'secret','agent'),'recovery can return to unexpired original login');
check($store->transaction(fn()=>$store->get('tx:'.$txId))['state']==='PASSWORD','return restores password stage');
check($recovery->request($id,'STAFF_FIXTURE','fixture-ip')==='ERROR','cancelled recovery cannot send OTP');
check(!$recovery->cancel($id,$txId,'secret','agent'),'recovery cancel cannot replay');
$id=$startRecovery();$r=$store->transaction(fn()=>$store->get('recovery:'.$id));$txId=$r['tx'];
$store->transaction(function()use($store,$txId){$tx=$store->get('tx:'.$txId);$tx['expires']=time()-1;$store->put('tx:'.$txId,$tx);});
check(!$recovery->cancel($id,$txId,'secret','agent'),'return never extends expired authorization');
$pdo->exec('UPDATE sys_config SET password_reset_email_enabled=0');
check($startRecovery()===null,'web recovery email configuration OFF also disables mobile recovery');
