<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){exit(2);}$root=dirname(__DIR__);foreach(['AdminStepUpException','TotpKeyring','TotpSecretCipher','Totp','AdminTotpFactorService'] as $f){require_once "$root/app/Auth/$f.php";}
use OneId\App\Auth\{AdminTotpFactorService,Totp,TotpKeyring,TotpSecretCipher,AdminStepUpException};
final class F73FakeOp{public array $factors=[];public array $audit=[];public bool $recovery=false;private int $next=1;public function beginTransaction(){}public function commit(){}public function rollback(){}
 public function admin_mfa_enrollment_context_for_update($a){return['u_type'=>1,'avail_status'=>1,'u_password'=>password_hash('Valid-pass-1!',PASSWORD_DEFAULT)];}
 public function admin_mfa_revoke_pending_factors($a){foreach($this->factors as &$f){if($f['admin_user_id']===$a&&$f['factor_status']==='PENDING')$f['factor_status']='REVOKED';}return 1;}
 public function admin_mfa_create_pending_factor(array $e){$id=$this->next++;$this->factors[$id]=$e+['factor_id'=>$id,'factor_type'=>'TOTP','factor_status'=>'PENDING','last_used_time_step'=>null];return$id;}
 public function admin_mfa_factor_for_update($id){return$this->factors[$id]??false;}
 public function admin_mfa_confirm_factor($id,$s){if(($this->factors[$id]['factor_status']??'')!=='PENDING')return 0;$this->factors[$id]['factor_status']='ACTIVE';$this->factors[$id]['last_used_time_step']=$s;return 1;}
 public function admin_mfa_record_factor_use($id,$s){if(($this->factors[$id]['factor_status']??'')!=='ACTIVE'||$this->factors[$id]['last_used_time_step']>=$s)return 0;$this->factors[$id]['last_used_time_step']=$s;return 1;}
 public function admin_step_up_has_valid_email_recovery_grant($a,$s,$b){return$this->recovery;}
 public function admin_mfa_revoke_factor($id){if(!in_array($this->factors[$id]['factor_status']??'', ['PENDING','ACTIVE'],true))return 0;$this->factors[$id]['factor_status']='REVOKED';return 1;}
 public function admin_mfa_clear_totp_preference($a){return 1;}public function syslog_record($e,$d,$ip){$this->audit[]=[$e,$d,$ip];return 1;}}
$dir=sys_get_temp_dir().'/oneid-f73-'.bin2hex(random_bytes(5));mkdir($dir,0700);$file="$dir/key.php";$src='<?php return '.var_export(['active_version'=>'v1','keys'=>['v1'=>base64_encode(random_bytes(32))]],true).';';file_put_contents($file,$src);chmod($file,0600);
try{$op=new F73FakeOp();$now=1234567890;$service=new AdminTotpFactorService($op,new TotpSecretCipher(TotpKeyring::fromFile($file)),static function()use(&$now){return$now;});$enroll=$service->enroll('0530-09','Valid-pass-1!','session','browser','127.0.0.1');$stored=$op->factors[$enroll['factor_id']];$encrypted=!str_contains($stored['encrypted_secret'],$enroll['secret']);$code=Totp::codeAt($enroll['secret'],$now);$confirmed=$service->confirm('0530-09',$enroll['factor_id'],$code,'session','browser','127.0.0.1');$now+=30;$verified=$service->verifyActive('0530-09',$enroll['factor_id'],Totp::codeAt($enroll['secret'],$now),'127.0.0.1');$replay=false;try{$service->verifyActive('0530-09',$enroll['factor_id'],Totp::codeAt($enroll['secret'],$now),'127.0.0.1');}catch(AdminStepUpException $e){$replay=$e->reason==='TOTP_VERIFICATION_FAILED';}$op->recovery=true;$revoked=$service->revoke('0530-09',$enroll['factor_id'],null,'session','browser','127.0.0.1','Recovery terkawal owner UAT');$audit=serialize($op->audit);$safe=!str_contains($audit,$enroll['secret'])&&!str_contains($audit,$code);$ok=$encrypted&&$confirmed['status']===1&&$verified['status']===1&&$replay&&$revoked['recovery_used']===true&&$safe;printf("%s encrypted=%s confirmed=%s verified=%s replay_rejected=%s recovery=%s audit_secret_free=%s\n",$ok?'PASS':'FAIL',$encrypted?'yes':'no',$confirmed['status']===1?'yes':'no',$verified['status']===1?'yes':'no',$replay?'yes':'no',$revoked['recovery_used']?'yes':'no',$safe?'yes':'no');exit($ok?0:1);}finally{if(is_file($file))unlink($file);if(is_dir($dir))rmdir($dir);}
