<?php
declare(strict_types=1);
$root=dirname(__DIR__);$page=(string)file_get_contents($root.'/admin/dashboard.php');$js=(string)file_get_contents($root.'/public/assetsM/js/login-banner-admin.js');$css=(string)file_get_contents($root.'/public/dist/css/oneid-login-banner-admin.css');$en=require $root.'/config/locales/en.php';$ms=require $root.'/config/locales/ms.php';$index=(string)file_get_contents($root.'/index.php');
$panel=function(string $id,string $nextId)use($page):string{$marker='<section class="tab-pane fade'.($id==='configuration_locale'?' active in':'').'" id="'.$id.'"';$start=strpos($page,$marker);if($start===false){return '';}if($nextId===''){$end=strpos($page,'<!-- /Row -->',$start);return substr($page,$start,$end===false?null:$end-$start);}$nextMarker='<section class="tab-pane fade'.($nextId==='configuration_locale'?' active in':'').'" id="'.$nextId.'"';$end=strpos($page,$nextMarker,$start+strlen($marker));return substr($page,$start,$end===false?null:$end-$start);};
$authentication=$panel('configuration_authentication','configuration_recovery');$recovery=$panel('configuration_recovery','configuration_admin_2fa');$adminMfa=$panel('configuration_admin_2fa','configuration_user_mfa');$userMfa=$panel('configuration_user_mfa','configuration_locale');$locale=$panel('configuration_locale','configuration_login_banner');$banner=$panel('configuration_login_banner','configuration_audit');$audit=$panel('configuration_audit','');
$checks=[
 'configuration navigation exposes an accessible login banner tab'=>str_contains($page,'id="configuration_login_banner_tab"')&&str_contains($page,'aria-controls="configuration_login_banner"')&&str_contains($page,'role="tabpanel"'),
 'configuration hierarchy groups all existing panels into requested primary and secondary tabs'=>str_contains($page,'data-configuration-group="general"')&&str_contains($page,'data-configuration-group="security"')&&str_contains($page,'data-configuration-group="mfa"')&&str_contains($page,'data-configuration-group="audit"')&&str_contains($page,'data-configuration-subtabs="general"')&&str_contains($page,'data-configuration-subtabs="security"')&&str_contains($page,'data-configuration-subtabs="mfa"'),
 'configuration group labels are complete in BM and English'=>isset($en['admin.configuration.general_group'],$en['admin.configuration.security_group'],$en['admin.configuration.mfa_group'],$en['admin.configuration.audit_group'],$ms['admin.configuration.general_group'],$ms['admin.configuration.security_group'],$ms['admin.configuration.mfa_group'],$ms['admin.configuration.audit_group']),
 'configuration state controller closes every top-level pane before opening one'=>str_contains($page,".configuration-tab-content > .tab-pane")&&str_contains($page,".removeClass('active in')")&&str_contains($page,".on('show.bs.tab'")&&str_contains($page,"$('#configuration_audit').addClass('active in')"),
 'each configuration transaction remains inside its owning panel'=>str_contains($authentication,'id="sso_config_save_button"')&&str_contains($recovery,'id="recovery_config_save_button"')&&str_contains($adminMfa,'id="admin_mfa_preference_save_button"')&&str_contains($userMfa,'id="user_mfa_global_save_button"')&&str_contains($locale,'id="default_locale_save_button"')&&str_contains($banner,'id="login_banner_draft_form"')&&str_contains($audit,'id="sso_config_history_body"'),
 'audit owns only its history table and user MFA subtabs remain nested in User 2FA'=>str_contains($audit,'id="sso_config_history_body"')&&!str_contains($audit,'user-2fa-subtabs')&&str_contains($userMfa,'class="nav nav-tabs user-2fa-subtabs"')&&str_contains($userMfa,'id="user_2fa_exemption_user_search"'),
 'draft form covers key order schedule locale alt text and both uploads'=>str_contains($page,'name="banner_key"')&&str_contains($page,'name="display_order"')&&str_contains($page,'login_banner_start')&&str_contains($page,'name="alt_text_ms"')&&str_contains($page,'name="alt_text_en"')&&str_contains($page,'name="banner_image_ms"')&&str_contains($page,'name="banner_image_en"'),
 'same-image control and local previews are explicit'=>str_contains($page,'name="same_image_for_english"')&&str_contains($page,'login_banner_preview_ms')&&str_contains($js,'FileReader'),
 'UI calls all seven guarded banner actions'=>str_contains($js,'admin_login_banner_list')&&str_contains($js,'admin_login_banner_create_draft')&&str_contains($js,'admin_login_banner_update_draft')&&str_contains($js,"'admin_login_banner_'+action")&&str_contains($js,'admin_login_banner_reorder'),
 'upload uses FormData while every request carries CSRF'=>str_contains($js,'new FormData(form)')&&str_contains($js,"'X-CSRF-Token':csrf")&&str_contains($js,'processData:options.form!==true'),
 'step-up rejection redirects to the approved security purpose'=>str_contains($page,'purpose=SECURITY_CONFIGURATION_CHANGE')&&str_contains($js,'xhr.status===403')&&str_contains($js,'window.location.href=stepUp'),
 'versioned mutations and complete reorder payload are retained'=>str_contains($js,'expected_version:item.configuration_version')&&str_contains($js,'expected_version:Number(input.dataset.version)')&&str_contains($js,'items_json:JSON.stringify(ordered)'),
 'dynamic server data is rendered as text rather than injected HTML'=>str_contains($js,'node.textContent=value')&&!str_contains($js,'.innerHTML'),
 'native prompt and confirm are replaced by localized SweetAlert approval'=>str_contains($js,"type:'input'")&&str_contains($js,'swal.showInputError')&&!str_contains($js,'window.prompt')&&!str_contains($js,'window.confirm'),
 'inactive or draft banners can be updated with optional immutable replacement assets'=>str_contains($js,"button(text('admin.banner.edit')")&&str_contains($js,'admin_login_banner_update_draft')&&str_contains($js,'expected_version'),
 'responsive image cards preserve the approved two-to-one ratio'=>str_contains($css,'aspect-ratio:2/1')&&str_contains($css,'@media(max-width:767px)'),
 'BM and English catalogs cover every banner UI key'=>count(array_filter(array_keys($en),static fn($key)=>str_starts_with($key,'admin.banner.')))===count(array_filter(array_keys($ms),static fn($key)=>str_starts_with($key,'admin.banner.')))&&count(array_filter(array_keys($en),static fn($key)=>str_starts_with($key,'admin.banner.')))>=48,
 'LB6 reader does not remove LB5 public static fallback'=>str_contains($index,'assetsM/images/banner6.png')&&str_contains($index,'assetsM/images/banner7.png')&&!str_contains($index,'LoginBannerService'),
];$fail=0;foreach($checks as $label=>$ok){echo($ok?'PASS ':'FAIL ').$label.PHP_EOL;if(!$ok)$fail++;}echo'RESULT checks='.count($checks).' failures='.$fail.PHP_EOL;exit($fail===0?0:1);
