<?php
declare(strict_types=1);
$root=dirname(__DIR__);$page=(string)file_get_contents($root.'/admin/dashboard.php');$js=(string)file_get_contents($root.'/public/assetsM/js/login-banner-admin.js');$css=(string)file_get_contents($root.'/public/dist/css/oneid-login-banner-admin.css');$en=require $root.'/config/locales/en.php';$ms=require $root.'/config/locales/ms.php';$index=(string)file_get_contents($root.'/index.php');
$checks=[
 'configuration navigation exposes an accessible login banner tab'=>str_contains($page,'id="configuration_login_banner_tab"')&&str_contains($page,'aria-controls="configuration_login_banner"')&&str_contains($page,'role="tabpanel"'),
 'draft form covers key order schedule locale alt text and both uploads'=>str_contains($page,'name="banner_key"')&&str_contains($page,'name="display_order"')&&str_contains($page,'login_banner_start')&&str_contains($page,'name="alt_text_ms"')&&str_contains($page,'name="alt_text_en"')&&str_contains($page,'name="banner_image_ms"')&&str_contains($page,'name="banner_image_en"'),
 'same-image control and local previews are explicit'=>str_contains($page,'name="same_image_for_english"')&&str_contains($page,'login_banner_preview_ms')&&str_contains($js,'FileReader'),
 'UI calls all seven guarded banner actions'=>str_contains($js,'admin_login_banner_list')&&str_contains($js,'admin_login_banner_create_draft')&&str_contains($js,'admin_login_banner_update_draft')&&str_contains($js,"'admin_login_banner_'+action")&&str_contains($js,'admin_login_banner_reorder'),
 'upload uses FormData while every request carries CSRF'=>str_contains($js,'new FormData(form)')&&str_contains($js,"'X-CSRF-Token':csrf")&&str_contains($js,'processData:options.form!==true'),
 'step-up rejection redirects to the approved security purpose'=>str_contains($page,'purpose=SECURITY_CONFIGURATION_CHANGE')&&str_contains($js,'xhr.status===403')&&str_contains($js,'window.location.href=stepUp'),
 'versioned mutations and complete reorder payload are retained'=>str_contains($js,'expected_version:item.configuration_version')&&str_contains($js,'expected_version:Number(input.dataset.version)')&&str_contains($js,'items_json:JSON.stringify(ordered)'),
 'dynamic server data is rendered as text rather than injected HTML'=>str_contains($js,'node.textContent=value')&&!str_contains($js,'.innerHTML'),
 'native prompt and confirm are replaced by localized SweetAlert approval'=>str_contains($js,"type:'input'")&&str_contains($js,'swal.showInputError')&&!str_contains($js,'window.prompt')&&!str_contains($js,'window.confirm'),
 'inactive or draft banners can be updated with optional immutable replacement assets'=>str_contains($js,"button(text('admin.banner.edit')")&&str_contains($js,'admin_login_banner_update_draft')&&str_contains($js,'expected_version'),
 'responsive image cards preserve the approved two-to-one ratio'=>str_contains($css,'aspect-ratio:2/1')&&str_contains($css,'@media(max-width:767px)'),
 'BM and English catalogs cover every banner UI key'=>count(array_filter(array_keys($en),static fn($key)=>str_starts_with($key,'admin.banner.')))===count(array_filter(array_keys($ms),static fn($key)=>str_starts_with($key,'admin.banner.')))&&count(array_filter(array_keys($en),static fn($key)=>str_starts_with($key,'admin.banner.')))>=48,
 'LB6 reader does not remove LB5 public static fallback'=>str_contains($index,'assetsM/images/banner6.png')&&str_contains($index,'assetsM/images/banner7.png')&&!str_contains($index,'LoginBannerService'),
];$fail=0;foreach($checks as $label=>$ok){echo($ok?'PASS ':'FAIL ').$label.PHP_EOL;if(!$ok)$fail++;}echo'RESULT checks='.count($checks).' failures='.$fail.PHP_EOL;exit($fail===0?0:1);
