<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){exit(2);}require_once dirname(__DIR__).'/lib/config.php';
$environment=strtolower(trim((string)oneid_config('ONEID_ENVIRONMENT','')));if(preg_match('/^[a-z][a-z0-9_-]{1,31}$/D',$environment)!==1){throw new RuntimeException('LB7_ENVIRONMENT_INVALID');}
$pdo=new PDO(DB_DSN,DB_USERNAME,DB_PASSWORD,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$tables=['login_banner','login_banner_translation','login_banner_asset','login_banner_locale_asset','login_banner_history'];$marks=implode(',',array_fill(0,count($tables),'?'));$check=$pdo->prepare("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ($marks)");$check->execute($tables);$present=array_fill_keys($tables,false);foreach($check->fetchAll(PDO::FETCH_COLUMN) as $table){$present[(string)$table]=true;}$schemaReady=!in_array(false,$present,true);$references=[];$databaseRows=0;
if($schemaReady){$query=$pdo->prepare('SELECT asset_id,banner_id,environment,image_filename,byte_size,sha256_digest,storage_status FROM login_banner_asset WHERE environment=:environment ORDER BY asset_id');$query->execute([':environment'=>$environment]);foreach($query->fetchAll() as $row){$filename=(string)$row['image_filename'];$references[$filename][]=$row;$databaseRows++;}}
$directory=oneid_public_path('login_banners');$files=[];if(is_dir($directory)){foreach(new FilesystemIterator($directory,FilesystemIterator::SKIP_DOTS) as $entry){if(!$entry->isFile()||$entry->isLink()||preg_match('/^login_banner_[a-f0-9]{32}\.webp$/D',$entry->getFilename())!==1){continue;}$files[$entry->getFilename()]=['filename'=>$entry->getFilename(),'bytes'=>$entry->getSize(),'sha256'=>hash_file('sha256',$entry->getPathname()),'modified_at'=>gmdate(DATE_ATOM,$entry->getMTime()),'age_days'=>max(0,(int)floor((time()-$entry->getMTime())/86400))];}}
$missing=[];$mismatch=[];foreach($references as $filename=>$rows){if(!isset($files[$filename])){$missing[]=['filename'=>$filename,'references'=>$rows];continue;}foreach($rows as $row){if((int)$row['byte_size']!==$files[$filename]['bytes']||!hash_equals((string)$row['sha256_digest'],(string)$files[$filename]['sha256'])){$mismatch[]=['filename'=>$filename,'asset_id'=>(int)$row['asset_id'],'expected_bytes'=>(int)$row['byte_size'],'actual_bytes'=>$files[$filename]['bytes'],'expected_sha256'=>(string)$row['sha256_digest'],'actual_sha256'=>$files[$filename]['sha256']];}}}
$allReferences=[];if($schemaReady){foreach($pdo->query('SELECT environment,image_filename FROM login_banner_asset')->fetchAll() as $row){$allReferences[(string)$row['image_filename']][]=(string)$row['environment'];}}
$orphans=[];if($schemaReady){foreach($files as $filename=>$file){if(!isset($references[$filename])){$outside=array_values(array_unique($allReferences[$filename]??[]));$orphans[]=$file+['classification'=>$outside===[]?'unreferenced_all_database_candidate':'referenced_other_environment_candidate','other_environments'=>$outside];}}}
$report=['contract'=>'LB7_RECONCILIATION_READ_ONLY_V1','generated_at'=>gmdate(DATE_ATOM),'environment'=>$environment,'schema'=>['available'=>$schemaReady,'tables'=>$present],'summary'=>['database_assets'=>$databaseRows,'filesystem_assets'=>count($files),'missing_references'=>count($missing),'integrity_mismatches'=>count($mismatch),'orphan_candidates'=>count($orphans)],'missing_references'=>$missing,'integrity_mismatches'=>$mismatch,'orphan_candidates'=>$orphans,'safety'=>['database_mutation'=>false,'filesystem_mutation'=>false,'automatic_deletion'=>false,'quarantine_minimum_age_days'=>90]];echo json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),PHP_EOL;
