<?php
declare(strict_types=1);
$root=dirname(__DIR__);$reconcile=(string)file_get_contents($root.'/tools/lb7_login_banner_reconciliation.php');$backup=(string)file_get_contents($root.'/tools/lb7_login_banner_backup.php');$quarantine=(string)file_get_contents($root.'/tools/lb7_login_banner_quarantine.php');$doc=(string)file_get_contents($root.'/docs/LB7_RECONCILIATION_BACKUP_QUARANTINE_ROLLBACK.md');$checks=[
 'reconciliation is CLI read-only and environment scoped'=>str_contains($reconcile,"PHP_SAPI!=='cli'")&&str_contains($reconcile,"oneid_config('ONEID_ENVIRONMENT','')")&&!preg_match('/\b(?:INSERT|UPDATE|DELETE|REPLACE)\b\s+/i',$reconcile),
 'reconciliation reports missing mismatch and orphan classes'=>str_contains($reconcile,"'missing_references'")&&str_contains($reconcile,"'integrity_mismatches'")&&str_contains($reconcile,"'unreferenced_all_database_candidate'")&&str_contains($reconcile,"'referenced_other_environment_candidate'"),
 'reconciliation makes no automatic deletion and requires 90-day quarantine'=>str_contains($reconcile,"'automatic_deletion'=>false")&&str_contains($reconcile,"'quarantine_minimum_age_days'=>90"),
 'backup defaults to check and create requires explicit change ID'=>str_contains($backup,"\$mode=\$argv[1]??'--check'")&&str_contains($backup,"ONEID_LB7_CHANGE_ID")&&str_contains($backup,"'--check','--create'"),
 'backup captures five tables assets checksums and pending restore evidence'=>str_contains($backup,'SHOW CREATE TABLE')&&str_contains($backup,"oneid_public_path('login_banners')")&&str_contains($backup,"'database_sha256'")&&str_contains($backup,"'restore_rehearsal'=>'PENDING'"),
 'backup and quarantine stay in private git-ignored storage'=>str_contains($backup,"oneid_storage_path('backups/login_banner/")&&str_contains($quarantine,"oneid_storage_path('quarantine/login_banner/")&&str_contains((string)file_get_contents($root.'/.gitignore'),'/storage/backups/*'),
 'quarantine is dry-run by default and double-gated for apply'=>str_contains($quarantine,"\$apply?'APPLY':'DRY-RUN'")&&str_contains($quarantine,'ONEID_LB7_QUARANTINE_AUTHORIZED')&&str_contains($quarantine,'ONEID_LB7_CHANGE_ID'),
 'quarantine refuses to classify assets while schema is unavailable'=>str_contains($quarantine,'LB7_QUARANTINE_SCHEMA_UNAVAILABLE')&&str_contains($reconcile,'if($schemaReady){foreach($files'),
 'quarantine only moves globally unreferenced assets aged 90 days'=>str_contains($quarantine,"==='unreferenced_all_database_candidate'")&&str_contains($quarantine,">=90")&&str_contains($quarantine,'rename($from,$to)'),
 'quarantine provides checksum-verified no-overwrite restore and compensation'=>str_contains($quarantine,'hash_equals(')&&str_contains($quarantine,'file_exists($to)')&&str_contains($quarantine,'foreach(array_reverse($moved)')&&str_contains($quarantine,"\$manifest['status']='restored'"),
 'runbook orders feature content code asset and schema rollback safely'=>str_contains($doc,'ONEID_LOGIN_BANNER_ENABLED=false')&&str_contains($doc,'Content rollback')&&str_contains($doc,'Code rollback')&&str_contains($doc,'Asset restore')&&str_contains($doc,'Schema down')&&str_contains($doc,'bukan langkah pertama'),
];$fail=0;foreach($checks as $label=>$ok){echo($ok?'PASS ':'FAIL ').$label.PHP_EOL;if(!$ok)$fail++;}echo'RESULT checks='.count($checks).' failures='.$fail.PHP_EOL;exit($fail===0?0:1);
