<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){exit(2);}$options=getopt('',['apply','restore:']);$apply=array_key_exists('apply',$options);$restore=trim((string)($options['restore']??''));if($apply&&$restore!==''){throw new RuntimeException('LB7_QUARANTINE_MODE_INVALID');}
ob_start();require __DIR__.'/lb7_login_banner_reconciliation.php';$report=json_decode((string)ob_get_clean(),true,512,JSON_THROW_ON_ERROR);$environment=(string)$report['environment'];$source=oneid_public_path('login_banners');$root=oneid_storage_path('quarantine/login_banner/'.$environment);$authorized=(getenv('ONEID_LB7_QUARANTINE_AUTHORIZED')?:'')==='true';$changeId=trim((string)(getenv('ONEID_LB7_CHANGE_ID')?:''));
if(($report['schema']['available']??false)!==true){throw new RuntimeException('LB7_QUARANTINE_SCHEMA_UNAVAILABLE');}
$write=static function(string $path,array $manifest):void{$temporary=$path.'.tmp';$data=json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR).PHP_EOL;if(file_put_contents($temporary,$data,LOCK_EX)===false||!chmod($temporary,0600)||!rename($temporary,$path)){@unlink($temporary);throw new RuntimeException('LB7_QUARANTINE_MANIFEST_FAILED');}};
if($restore!==''){if(!$authorized||preg_match('/^[0-9]{8}T[0-9]{6}-[a-f0-9]{8}$/D',$restore)!==1){throw new RuntimeException('LB7_RESTORE_AUTHORIZATION_INVALID');}$batch=$root.'/'.$restore;$manifestPath=$batch.'/manifest.json';$manifest=json_decode((string)file_get_contents($manifestPath),true,512,JSON_THROW_ON_ERROR);if(($manifest['environment']??'')!==$environment||($manifest['status']??'')!=='quarantined'){throw new RuntimeException('LB7_RESTORE_MANIFEST_INVALID');}$moved=[];try{foreach($manifest['files'] as $file){$filename=basename((string)$file['filename']);$from=$batch.'/'.$filename;$to=$source.'/'.$filename;if(!is_file($from)||!hash_equals((string)$file['sha256'],(string)hash_file('sha256',$from))||file_exists($to)||!rename($from,$to)){throw new RuntimeException('LB7_RESTORE_FILE_INVALID');}$moved[]=[$to,$from];}}catch(Throwable $error){foreach(array_reverse($moved) as [$to,$from]){@rename($to,$from);}throw $error;}$manifest['status']='restored';$manifest['restored_at']=gmdate(DATE_ATOM);$manifest['restore_change_id']=$changeId;$write($manifestPath,$manifest);printf("RESTORED batch=%s files=%d\n",$restore,count($moved));exit(0);}
$candidates=array_values(array_filter($report['orphan_candidates'],static fn(array $item):bool=>($item['classification']??'')==='unreferenced_all_database_candidate'&&(int)($item['age_days']??0)>=90));printf("%s environment=%s candidates=%d minimum_age_days=90 automatic_deletion=false\n",$apply?'APPLY':'DRY-RUN',$environment,count($candidates));foreach($candidates as $item){printf("%s age_days=%d bytes=%d sha256=%s\n",$item['filename'],$item['age_days'],$item['bytes'],$item['sha256']);}if(!$apply){exit(0);}if(!$authorized||preg_match('/^[A-Z0-9][A-Z0-9._-]{7,127}$/D',$changeId)!==1||$candidates===[]){throw new RuntimeException('LB7_QUARANTINE_AUTHORIZATION_INVALID');}
$batchId=gmdate('Ymd\THis').'-'.bin2hex(random_bytes(4));$batch=$root.'/'.$batchId;if(!mkdir($batch,0700,true)||!chmod($batch,0700)){throw new RuntimeException('LB7_QUARANTINE_TARGET_FAILED');}$manifestPath=$batch.'/manifest.json';$manifest=['contract'=>'LB7_QUARANTINE_MANIFEST_V1','batch_id'=>$batchId,'environment'=>$environment,'change_id'=>$changeId,'minimum_age_days'=>90,'status'=>'planned','created_at'=>gmdate(DATE_ATOM),'files'=>$candidates,'automatic_deletion'=>false];$write($manifestPath,$manifest);$moved=[];try{foreach($candidates as $file){$filename=basename((string)$file['filename']);$from=$source.'/'.$filename;$to=$batch.'/'.$filename;if(!is_file($from)||filesize($from)!==(int)$file['bytes']||!hash_equals((string)$file['sha256'],(string)hash_file('sha256',$from))||file_exists($to)||!rename($from,$to)||!chmod($to,0600)){throw new RuntimeException('LB7_QUARANTINE_CANDIDATE_CHANGED');}$moved[]=[$to,$from];}}catch(Throwable $error){foreach(array_reverse($moved) as [$to,$from]){@rename($to,$from);}$manifest['status']='rolled_back';$manifest['failed_at']=gmdate(DATE_ATOM);$write($manifestPath,$manifest);throw $error;}$manifest['status']='quarantined';$manifest['quarantined_at']=gmdate(DATE_ATOM);$write($manifestPath,$manifest);printf("QUARANTINED batch=%s files=%d deletion=false\n",$batchId,count($moved));
