<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){exit(2);}require_once dirname(__DIR__).'/lib/config.php';
$checks=[];$environment=strtolower(trim((string)oneid_config('ONEID_ENVIRONMENT','')));$checks['environment_is_staging']=$environment==='staging';$checks['dynamic_flag_is_off_before_activation']=filter_var(oneid_config('ONEID_LOGIN_BANNER_ENABLED','false'),FILTER_VALIDATE_BOOLEAN)===false;$changeId=trim((string)(getenv('ONEID_LB8_CHANGE_ID')?:''));$checks['change_id']=preg_match('/^[A-Z0-9][A-Z0-9._-]{7,127}$/D',$changeId)===1;
$pdo=null;try{$pdo=new PDO(DB_DSN,DB_USERNAME,DB_PASSWORD,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$checks['database_connection']=(string)$pdo->query('SELECT DATABASE()')->fetchColumn()!=='';}catch(Throwable){$checks['database_connection']=false;}
$tables=['login_banner','login_banner_translation','login_banner_asset','login_banner_locale_asset','login_banner_history'];$checks['schema_ready']=false;if($pdo instanceof PDO){$marks=implode(',',array_fill(0,5,'?'));$statement=$pdo->prepare("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ($marks)");$statement->execute($tables);$checks['schema_ready']=(int)$statement->fetchColumn()===5;}
$assetDirectory=oneid_public_path('login_banners');$stagingDirectory=oneid_storage_path('runtime/login-banner-staging');$checks['webp_runtime']=extension_loaded('gd')&&function_exists('imagewebp')&&in_array('image/webp',get_extension_funcs('gd')===false?[]:['image/webp'],true);if(extension_loaded('gd')&&function_exists('imagetypes')){$checks['webp_runtime']=(imagetypes()&IMG_WEBP)===IMG_WEBP;}$checks['asset_directory_ready']=is_dir($assetDirectory)&&is_readable($assetDirectory)&&is_writable($assetDirectory)&&!is_link($assetDirectory);$checks['private_staging_ready']=is_dir($stagingDirectory)&&is_readable($stagingDirectory)&&is_writable($stagingDirectory)&&!is_link($stagingDirectory);
$backupPath=trim((string)(getenv('ONEID_LB8_BACKUP_EVIDENCE')?:''));$backup=is_file($backupPath)?json_decode((string)file_get_contents($backupPath),true):null;$backupDirectory=is_array($backup)?dirname($backupPath):'';$databaseFile=is_array($backup)?$backupDirectory.'/'.basename((string)($backup['database_file']??'')):'';$checks['backup_evidence_contract']=is_array($backup)&&($backup['contract']??'')==='LB7_BACKUP_EVIDENCE_V1'&&($backup['environment']??'')==='staging'&&($backup['change_id']??'')===$changeId;$checks['backup_database_checksum']=$databaseFile!==''&&is_file($databaseFile)&&is_string($backup['database_sha256']??null)&&hash_equals((string)$backup['database_sha256'],(string)hash_file('sha256',$databaseFile));$checks['isolated_restore_pass']=($backup['restore_rehearsal']??'')==='PASS'&&($backup['exact_row_count_reconciliation']??'')==='PASS'&&($backup['asset_checksum_reconciliation']??'')==='PASS';
$uatPath=trim((string)(getenv('ONEID_LB8_UAT_EVIDENCE')?:''));$uat=is_file($uatPath)?json_decode((string)file_get_contents($uatPath),true):null;$required=['same_asset_ms_en','distinct_asset_ms_en','english_explicit_fallback','missing_asset_static_fallback','invalid_upload_rejected','schedule_boundary_asia_kuala_lumpur','reorder','inactivate','rollback','concurrent_admin_stale_rejected','desktop','mobile','slow_network','cache_hard_refresh','password_login','mydigitalid_login','accessibility','audit_correlation','reconciliation_clean'];$checks['uat_evidence_contract']=is_array($uat)&&($uat['contract']??'')==='LB8_STAGING_UAT_EVIDENCE_V1'&&($uat['environment']??'')==='staging'&&($uat['change_id']??'')===$changeId&&preg_match('/^[a-f0-9]{40}$/D',(string)($uat['tested_commit']??''))===1;$checks['uat_matrix_pass']=$checks['uat_evidence_contract'];foreach($required as $result){$checks['uat_matrix_pass']=$checks['uat_matrix_pass']&&($uat['results'][$result]??'')==='PASS';}$checks['owner_acceptance']=($uat['owner_acceptance']??'')==='GO';
$checks['reconciliation_clean']=false;if($checks['schema_ready']){try{ob_start();require __DIR__.'/lb7_login_banner_reconciliation.php';$reconciliation=json_decode((string)ob_get_clean(),true,512,JSON_THROW_ON_ERROR);$summary=$reconciliation['summary']??[];$checks['reconciliation_clean']=(int)($summary['missing_references']??-1)===0&&(int)($summary['integrity_mismatches']??-1)===0;}catch(Throwable){if(ob_get_level()>0){ob_end_clean();}$checks['reconciliation_clean']=false;}}
foreach($checks as $name=>$passed){printf("%s %s\n",$passed?'PASS':'BLOCKED',$name);}$blocked=count(array_filter($checks,static fn(bool $passed):bool=>!$passed));printf("DECISION=%s checks=%d blocked=%d mutations=0 secrets_output=0\n",$blocked===0?'GO_STAGING_ACTIVATION':'NO_GO',count($checks),$blocked);exit($blocked===0?0:1);
