<?php
declare(strict_types=1);
$root=dirname(__DIR__);$gate=(string)file_get_contents($root.'/tools/lb8_staging_activation_gate.php');$attest=(string)file_get_contents($root.'/tools/lb8_attest_backup_evidence.php');$template=json_decode((string)file_get_contents($root.'/docs/templates/LB8_STAGING_UAT_EVIDENCE.example.json'),true,512,JSON_THROW_ON_ERROR);$doc=(string)file_get_contents($root.'/docs/LB8_STAGING_UAT_DAN_CONTROLLED_ACTIVATION.md');$runtime=(string)file_get_contents($root.'/config/runtime.php');$checks=[
 'gate is CLI read-only and emits explicit no-go/go'=>str_contains($gate,"PHP_SAPI!=='cli'")&&str_contains($gate,"'GO_STAGING_ACTIVATION':'NO_GO'")&&str_contains($gate,'mutations=0')&&!preg_match('/\b(?:INSERT|UPDATE|DELETE|REPLACE)\b\s+/i',$gate),
 'gate requires exact staging environment flag-off and change ID'=>str_contains($gate,"\$environment==='staging'")&&str_contains($gate,"ONEID_LOGIN_BANNER_ENABLED")&&str_contains($gate,"===false")&&str_contains($gate,'ONEID_LB8_CHANGE_ID'),
 'gate requires all five schema tables and writable isolated directories'=>str_contains($gate,"'login_banner_history'")&&str_contains($gate,"===5")&&str_contains($gate,"oneid_public_path('login_banners')")&&str_contains($gate,"oneid_storage_path('runtime/login-banner-staging')"),
 'directory gate binds exact www-data owner and approved modes'=>str_contains($gate,"posix_getpwnam('www-data')")&&str_contains($gate,'$requiredMode')&&str_contains($gate,'0755')&&str_contains($gate,'0700'),
 'gate requires backup checksum and three restore pass signals'=>str_contains($gate,'LB7_BACKUP_EVIDENCE_V1')&&str_contains($gate,"hash_file('sha256',\$databaseFile)")&&str_contains($gate,"'restore_rehearsal']??'')==='PASS'")&&str_contains($gate,"'exact_row_count_reconciliation']??'')==='PASS'")&&str_contains($gate,"'asset_checksum_reconciliation']??'')==='PASS'"),
 'UAT template is pending-safe and contains nineteen required results'=>($template['owner_acceptance']??'')==='PENDING'&&count($template['results']??[])===19&&count(array_filter($template['results'],static fn($value)=>$value==='PENDING'))===19,
 'gate binds UAT evidence to staging change ID and tested commit'=>str_contains($gate,'LB8_STAGING_UAT_EVIDENCE_V1')&&str_contains($gate,"(\$uat['change_id']??'')===\$changeId")&&str_contains($gate,"^[a-f0-9]{40}$")&&str_contains($gate,"owner_acceptance']??'')==='GO'"),
 'gate independently reruns reconciliation and blocks missing or mismatched assets'=>str_contains($gate,'lb7_login_banner_reconciliation.php')&&str_contains($gate,"summary['missing_references']")&&str_contains($gate,"summary['integrity_mismatches']"),
 'backup attestation verifies both dumps restore cleanup and every asset before update'=>str_contains($attest,'LB7_BACKUP_EVIDENCE_V1')&&substr_count($attest,"hash_file('sha256'")>=4&&str_contains($attest,"'restore_target_dropped']??'')==='yes'")&&str_contains($attest,"'asset_checksum_reconciliation']='PASS'")&&str_contains($attest,'.tmp'),
 'committed dynamic default remains off'=>str_contains($runtime,"'ONEID_LOGIN_BANNER_ENABLED' => 'false'"),
 'runbook separates preparation gate activation observation and rollback'=>str_contains($doc,'Fasa A — Preparation')&&str_contains($doc,'Fasa B — Gate')&&str_contains($doc,'Fasa C — Activation')&&str_contains($doc,'Fasa D — Observation')&&str_contains($doc,'ONEID_LOGIN_BANNER_ENABLED=false'),
];$fail=0;foreach($checks as $label=>$ok){echo($ok?'PASS ':'FAIL ').$label.PHP_EOL;if(!$ok)$fail++;}echo'RESULT checks='.count($checks).' failures='.$fail.PHP_EOL;exit($fail===0?0:1);
