<?php
declare(strict_types=1);require_once dirname(__DIR__).'/lib/auth_security.php';require_once dirname(__DIR__).'/app/User/UserPasswordChangeException.php';require_once dirname(__DIR__).'/app/User/UserPasswordChangeService.php';
use OneId\App\User\UserPasswordChangeException;use OneId\App\User\UserPasswordChangeService;
final class Uc2Fake{public array $user;public int $begins=0,$commits=0,$rollbacks=0,$passwords=0,$tokens=0,$otp=0,$adds=0,$audits=0;public bool $failToken=false;function __construct(){$this->user=['u_id'=>'USER1','u_password'=>oneid_password_hash('Current!Pass123'),'password_change_required'=>1,'avail_status'=>1];}function beginTransaction(){$this->begins++;}function commit(){$this->commits++;}function rollback(){$this->rollbacks++;}function get_user_password_change_for_update($id){return $this->user;}function get_password_history_hashes($id,$limit){return [];}function record_password_history($id,$hash){return 1;}function prune_password_history($id,$keep){return 0;}function set_user_password($id,$p,$r){$this->passwords++;return 1;}function update_whole_token_status($id,$s){$this->tokens++;return 2;}function otp_invalidate_active($id){$this->otp++;return 1;}function add_new_token($t,$id,$d){$this->adds++;return $this->failToken?0:1;}function syslog_record($e,$d,$ip){$this->audits++;return 1;}}
$n=0;$f=0;$ok=function($v,$d)use(&$n,&$f){$n++;if(!$v)$f++;printf("%s: %s\n",$v?'PASS':'FAIL',$d);};
$fake=new Uc2Fake();$r=(new UserPasswordChangeService($fake))->change('USER1','Current!Pass123','Different!Pass456','Different!Pass456','browser','127.0.0.1');
$ok($r['code']==='UC4_PASSWORD_CHANGED_SESSION_ROTATED'&&isset($r['replacement_token']),'valid change returns correlated replacement token');$ok($fake->passwords===1&&$fake->tokens===1&&$fake->otp===1&&$fake->adds===1&&$fake->audits===1&&$fake->commits===1,'password, tokens, OTP, replacement and audit share one commit');
$reuse=new Uc2Fake();try{(new UserPasswordChangeService($reuse))->change('USER1','Current!Pass123','Current!Pass123','Current!Pass123','browser','ip');$ok(false,'current password reuse rejected');}catch(UserPasswordChangeException $e){$ok($e->reason==='UC2_PASSWORD_REUSE_CURRENT'&&$reuse->rollbacks===1,'current password reuse rejected and rolled back');}
$failure=new Uc2Fake();$failure->failToken=true;try{(new UserPasswordChangeService($failure))->change('USER1','Current!Pass123','Different!Pass456','Different!Pass456','browser','ip');$ok(false,'replacement failure rolls back');}catch(UserPasswordChangeException $e){$ok($e->reason==='UC2_REPLACEMENT_TOKEN_FAILED'&&$failure->rollbacks===1&&$failure->commits===0,'replacement failure rolls back all mutations');}
$wrong=new Uc2Fake();try{(new UserPasswordChangeService($wrong))->change('USER1','Wrong!Pass123','Different!Pass456','Different!Pass456','browser','ip');$ok(false,'wrong current password rejected');}catch(UserPasswordChangeException $e){$ok($e->reason==='UC2_CURRENT_PASSWORD_INVALID'&&$wrong->passwords===0,'wrong current password is rejected before mutation');}
printf("RESULT: checks=%d failures=%d\n",$n,$f);exit($f===0?0:1);
